<html>

<head>
<meta http-equiv="Content-Type"
content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage Express 2.0">
<title>Unrealed.net Portals</title>
</head>

<body background="http://www.unrealed.net/images/back_01.jpg" topmargin="0" leftmargin="0" rules="none">

<table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
<style><!--
A:link {text-decoration: none; color: #00ffff}
A:visited {text-decoration:none; color:#00ffff}
A:hover {text-decoration:none; color:#00bfff}
--></style>    
 <tr>
  <td><table border="0" cellpadding="0" cellspacing="0" width="100%" border="0" text="#3EADB7">
   <tr>
    <td width="450"><img src="http://www.unrealed.net/images/ued_logo_top.jpg" width="450" height="119"></td>
    <td colspan="2" background="http://www.unrealed.net/images/ued_bar_middle.jpg">
     <table border="0" cellpadding="0" cellspacing="0" width="100%" border="0" text="#3EADB7">
      <tr> 
       <td><img src="http://www.unrealed.net/images/ued_bar_left.jpg" align="left" hspace="0" width="59" height="119"></td>
       <td><br></td>
       <td align="right"><img src="http://www.unrealed.net/images/ued_bar_right.jpg" width="59" height="119"></td>
      </tr>
     </table>
    </td>
   </tr>
  </table>
  <table border="0" cellpadding="0" cellspacing="0" width="100%" border="0" text="#3EADB7">
   <tr>
    <td><img src="http://www.unrealed.net/images/ued_logo_bottom.jpg" width="218" height="81"></td>
    <td>
     <table border="0" cellpadding="0" cellspacing="0" width="100%" border="0" text="#3EADB7">
      <tr>
       <td align="right"><img src="http://www.unrealed.net/images/head_menu_01.jpg" width="30" height="30"></td>
       <td>
        <table border="0" cellpadding="0" cellspacing="0" width="100%" background="http://www.unrealed.net/images/head_menu_back.jpg" text="#3EADB7">
         <tr>
          <td align="center" valign="top">
           <table border="0" cellpadding="0" cellspacing="0" border="0" text="#3EADB7">
            <tr>
             <td><a href="http://www.unrealed.net/index.phtml"><font face="verdana" size="1"><strong>News</font></strong></a></td>
             <td><img src="http://www.unrealed.net/images/head_menu_break.jpg" width="10" height="30"></td>
             <td><a href="http://www.unrealed.net/submit.phtml"><font face="verdana" size="1"><strong>Submissions</font></strong></a></td>
             <td><img src="http://www.unrealed.net/images/head_menu_break.jpg" width="10" height="30"></td>
             <td><a href="http://www.unrealed.net/prefabs.phtml"><font face="verdana" size="1"><strong>Prefabs</font></strong></a></td>
             <td><img src="http://www.unrealed.net/images/head_menu_break.jpg" width="10" height="30"></td>
             <td><a href="http://www.unrealed.net/levels.phtml"><font face="verdana" size="1"><strong>Levels</font></strong></a></td>
             <td><img src="http://www.unrealed.net/images/head_menu_break.jpg" width="10" height="30"></td>
             <td><a href="http://www.unrealed.net/staff.phtml"><font face="verdana" size="1"><strong>Staff</font></strong></a></td>
             <td><img src="http://www.unrealed.net/images/head_menu_break.jpg" width="10" height="30"></td>
             <td><a href="http://www.unrealed.net/links.phtml"><font face="verdana" size="1"><strong>Links</strong></font></a></td>
            </tr>
           </table>
          </td>
          <td align="right"><img src="http://www.unrealed.net/images/head_menu_02.jpg" width="30" height="30"></td>
         </tr>
        </table>
       </td>
      </tr>
     </table>
    </td>
   </tr>
  </table>
 </td>
</tr>
</table>

<table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
 <tr>
  <td>
   <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
    <tr>
    </tr>
   </table>
  </td>
 </tr>
 <tr>
  <td><img src="http://www.unrealed.net/images/head_break.jpg" width="15" height="15"></td>
 </tr>
 <tr>
  <td>
   <table valign=top border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
    <tr>
     <td valign=top width="125">
      <table valign=top border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
 <tr>
  <td><img src="http://www.unrealed.net/images/menu_bord_tl.jpg" width="15" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_t.jpg" width="95" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_tr.jpg" width="15" height="15"></td>
 </tr>
 <tr>
  <td background="http://www.unrealed.net/images/menu_bord_s.jpg"><br></td>
  <td>
   <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Main</font></strong></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/index.phtml">News</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/submit.phtml">Submissions</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/prefabs.phtml">Prefabs</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/staff.phtml">Staff</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/levels.phtml">Levels</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/links.phtml">Links</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Editing</font></strong></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/edmain.phtml">Main Page</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/edtutes.phtml">Tutorials</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/errors.phtml">Ued Errors</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/edfiles.phtml">Files</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/shortcut.phtml">Shortcut Keys</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/mirc.phtml">#unrealed</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/timnotes.phtml">Reference</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="mailto:millennium@unrealnation.com?subject=Edit_Master">Edit Master</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Scripting</font></strong></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/usmain.phtml">Main Page</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/ustutes.phtml">Tutorials</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/classes.phtml">Online Classes</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/timnotes.phtml">Reference</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="mailto:millennium@planetunreal.com?subject=Code_Master">Code Master</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Modelling</font></strong></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/mdmain.phtml">Main Page</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/mdtutes.phtml">Tutorials</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/timnotes.phtml">Reference</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="mailto:jaytan@pl.jaring.my?subject=Model_Master">Model Master</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Skinning</font></strong></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/skintutes/skinfaq.phtml">Skinning Guide</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Prefabs</font></strong></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/prefabs/brushes.phtml">Brushes</a></strong></font></td></tr>
    <tr><td><font size="1" face="verdana"><strong><a href="http://www.unrealed.net/prefabs/textures.phtml">Textures</a></strong></font></td></tr>
    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>

    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Hosted Sites</font></strong></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/muzo">Heph's Music</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/3dme">3D Model Emporium</A></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/millennium">Millennium</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/vermoord">VerMoorD</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealed.net/outhouse">Rage TC</a></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="hostinfo.html">Hosting Info</a></strong></font></td></tr>

    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>
    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Network Sites</strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.unrealnation.com">Unrealnation</A></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.sume.com">S.U.M.E.</A></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.honorguards.com">Honor Guards</A></strong></font></td></tr>
    <tr><td><font size="0" face="verdana"><strong><a href="http://www.worldofdreams.com">World of Dreams</A></strong></font></td></tr>

    <tr><td><img src="http://www.unrealed.net/images/menu_bord_m.jpg" width="95" height="15"></td></tr>
    <tr><td><font color="#00bfff" face="verdana" size="1"><strong>Your Unrealed.net</strong></font></td></tr>
    <tr><td><font color="#DDE3F6" face="verdana" size="0"></strong>If you have a Tutorial, Tip, Hint or whatever! then feel free to <a href="submit.phtml">send it down</a>, and we will be happy to post it on the site.</strong></font></td></tr>
   </table>
  </td>
  <td background="http://www.unrealed.net/images/menu_bord_rs.jpg"><br>
  </td>
 </tr>
 <tr>
  <td><img src="http://www.unrealed.net/images/menu_bord_bl.jpg" width="15" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_b.jpg" width="95" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_br.jpg" width="15" height="15"></td>
 </tr>
</table>
     </td>
     <td width="15"><br></td>
     <td valign="top">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
       <tr>
        <td width="100%">
         <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
          <tr>
           <td valign="top">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
             <tr>
              <td valign="top">
               <table border="0" cellpadding="0" cellspacing="0" width="500" text="#3EADB7">
 <tr>
  <td><img src="http://www.unrealed.net/images/menu_bord_tl.jpg" width="15" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_t_long.jpg" width="470" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_tr.jpg" width="15" height="15"></td>
 </tr>
 <tr>
  <td background="http://www.unrealed.net/images/menu_bord_s.jpg"><img src="http://www.unrealed.net/images/menu_bord_s.jpg" width="15" height="1"></td>
  <td>

<IFRAME height="62" width="470" marginheight="0" marginwidth="0" border="0" frameborder="0" scrolling="no" src="http://ads.gamesmania.com/adsamples/default.asp?target=alliance&amp;target=unrealnation&amp;t arget=zzz"> 
<script language="JavaScript" src="http://ads.gamesmania.com/adsamples/adsjs.asp?target=alliance&amp;target=unrealnation&amp;target=zzz"></script>
</IFRAME>                    

  </td>
  <td width="15" background="http://www.unrealed.net/images/menu_bord_rs.jpg"><img src="http://www.unrealed.net/images/menu_bord_rs.jpg" width="15" height="1"></td>
 </tr>
 <tr>
  <td><img src="http://www.unrealed.net/images/menu_bord_bl.jpg" width="15" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_b_long.jpg" width="470" height="15"></td>
  <td><img src="http://www.unrealed.net/images/menu_bord_br.jpg" width="15" height="15"></td>
 </tr>
</table>
              </td>
             </tr>
             <tr><td><br></td></tr>
             <tr>
              <td>
               <table border="0" cellpadding="0" cellspacing="0" width="100%" text="#3EADB7">
                <tr>
                 <td><img src="http://www.unrealed.net/images/edit.jpg"></td></tr><tr><td><br>
                 </td>
                </tr>
                <tr>
                 <td width="100%" colspan="3">
                  <table border="0" cellpadding="0" cellspacing="0" bgcolor="#53657B" text="#3EADB7">
 <tr>
  <td bgcolor="#53657B"><img src="http://www.unrealed.net/images/news_bord/tl.jpg" width="10" height="10"></td>
  <td background="http://www.unrealed.net/images/news_bord/ts.jpg"><img src="http://www.unrealed.net/images/news_bord/ts.jpg" width="2" height="10"></td>
  <td bgcolor="#53657B"><img src="http://www.unrealed.net/images/news_bord/tr.jpg" width="10" height="10"></td>
 </tr>
 <tr>
  <td background="http://www.unrealed.net/images/news_bord/ls.jpg"><img src="http://www.unrealed.net/images/news_bord/ls.jpg" width="10" height="2"></td>
  <td>
   <table border="0" cellpadding="0" cellspacing="0" bgcolor="#53678B" text="#3EADB7">
    <tr>
<td>

<font face="verdana" color="#00ffff" size=4>Portals</font><br>
<font color="#E6E6E6"><P>By: Sharky</P>
<P><a HREF="A HREF="mailto:jneta@ez-net.com?subject=Tutorials">M</a></P>
<P>Dated: 10/6/98 </P>
<p>Click <a href="portals/print.html">here</a> for a printable version of this Tutorial.</p>


Where to start? well first off make a basic level.. if you dont know how to do this read a baisc tutorial (ill be writing one soon).. ok you have your big cube level... add your player start and some lights... next make your builder cube 200x200x200 and subtract it from a side.. next subtract from another wall (see pic1).
<br>
<img src="portals/pic1.JPG"><br>
<small>The test room with the holes</small><br>

The test room with the holes Now select sheet builder set the properties to Y-Wall(or X-Wall depending on the orientation of the holes in the wall) and set the U and V to 200.. this will act as a barrier for your portal and the rest of your level.. move it in front of one of the holes in the wall (make sure its lined up perfectly).. now select a nice lookin texture (i suggest picking from the GenWarp set) now that you have the texture you want hit the add special button (pic2) and use the same settings as in (pic3)...
<br>
<img src="portals/pic2.JPG"</a><br>
<small>Hit this button</small><br>

<br>
<img src="portals/pic3.JPG"<br>
<small>Use these settings</small><br>

Move the builder brush to the other hole and repeat... Next goto classes and pick ZoneInfo->WarpZoneInfo and add one inside each of the holes you made... now set the properties of one of the WarpZones to Dest of Warp1 and Src of Warp2... now pick the other WarpZone and set it to Dest Warp2 and Src Warp1 (see pic4).


<br>
<img src="portals/pic4.JPG"><br>
<small>The Property box(double click the ZoneInfo to pop it up)</small><br>

Now rebuild and your all set.. save your level and test it out

<br>
<img src="portals/finaled.JPG"><br>
<small>The final level in UnrealED</small><br>

<br>
<img src="portals/finalgame.JPG"><br>
<small>The level in the game, note the hall of mirrors effect (its easier to see without a texture on the sheets)</small><br>
                  </td>
                      </tr>
   </table>
  </td>
  <td background="images/news_bord/rs.jpg"><img src="http://www.unrealed.net/images/news_bord/rs.jpg" width="10" height="2"></td>
 </tr>
 <tr>
  <td bgcolor="#53657B"><img src="http://www.unrealed.net/images/news_bord/bl.jpg" width="10" height="10"></td>
  <td background="http://www.unrealed.net/images/news_bord/bs.jpg"><img src="http://www.unrealed.net/images/news_bord/bs.jpg" width="2" height="10"></td>
  <td bgcolor="#53657B"><img src="http://www.unrealed.net/images/news_bord/br.jpg" width="10" height="10"></td>
 </tr>
</table>
                 </td>
                </tr>
               <tr><td><br></td></tr>
              <tr><td><br></td>
              </tr>
             </td>
            </tr>
           </table>
          </td>
         <td width="10"><img src="http://www.unrealed.net/images/back_space.jpg"></td>
        </tr>
       </table>
      </td>
     </tr>
    </table>
   </td>
   <td width="15"><font color="#E6E6E6"><img src="http://www.unrealed.net/images/back_space.jpg" width="15" height="1"></font></td>
  </tr>
 </table>
 </td>
 </tr>
 </table>
 </td>
 </tr>
</table>
<p><br><br><br><br></p>
<p align=center> <font face="verdana" size="1" color="#00ffff"><strong>Site Design | Coding | Graphics by <font color="00bfff">| Millennium 2002 |</font> <br> Unreal and UnrealED are Copyright Epic Megagames 1998</font></p>
</body>
</html>
